import Head from 'next/head';


import DesignedHero from '@/components/DesignedHero';
import HeroRat from '@/components/Hero';
import HighQualityVideos from '@/components/HighQualityVideos';
import UserComments from '@/components/UserComments';
import PayOnce from '@/components/PayOnce';
import Faqs from '@/components/Faqs';

export default function Home() {
  return (
    <>
      <Head>
        <title>Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/HeroRat.png" />
      </Head>
      <main className=" min-h-screen">
        <HeroRat />
        <HighQualityVideos />
        <DesignedHero />
        <UserComments />
        <PayOnce />
        <Faqs />
      </main>
    </>
  );
}
